### PR TITLE
HW2

### PR DESCRIPTION
**Pull request by adeeb-mcst**
HW2

### CODE REVIEW

**Comment by adeeb-mcst** [comment]
HW2

**Comment by adeeb-mcst** [comment]
HW#3

**Comment by Jaafar-Abdullah** [comment]
Great job,
try to use prototype when you create a function in the object instead of creating the function inside the object

**Comment by Jaafar-Abdullah** [comment]
and please if you can delete 
.DS_Store from your laptop and then push it again

**Pull request closed without merging**
